import type { Wood } from './types';

export const WOODS: Wood[] = [
  // ─── DOMESTIC ───────────────────────────────────────────────
  {
    id: 'hard-maple',
    name: 'Hard Maple',
    color: '#E8D9B8',
    oiledColor: '#D4B896',
    textureId: 'maple',
    foodSafe: true,
    janka: 1450,
    densityLbFt3: 44,
    group: 'domestic',
    notes: 'Default kitchen hardwood. Prefer hard maple over soft maple.',
  },
  {
    id: 'soft-maple',
    name: 'Soft Maple',
    color: '#EDE0C8',
    oiledColor: '#D9C9A8',
    textureId: 'maple',
    foodSafe: true,
    janka: 950,
    densityLbFt3: 38,
    group: 'domestic',
    notes: 'Dishes faster than hard maple — prefer hard maple.',
  },
  {
    id: 'walnut',
    name: 'Black Walnut',
    color: '#5C4033',
    oiledColor: '#3E2A20',
    textureId: 'walnut',
    foodSafe: true,
    janka: 1010,
    densityLbFt3: 38,
    group: 'domestic',
  },
  {
    id: 'walnut-sapwood',
    name: 'Walnut Sapwood',
    color: '#A68B6C',
    oiledColor: '#8A7358',
    textureId: 'walnut',
    foodSafe: true,
    janka: 1010,
    densityLbFt3: 38,
    group: 'domestic',
    notes: 'Light outer wood of walnut — pairs well with dark walnut.',
  },
  {
    id: 'cherry',
    name: 'Cherry',
    color: '#A0522D',
    oiledColor: '#8B4513',
    textureId: 'cherry',
    foodSafe: true,
    janka: 950,
    densityLbFt3: 35,
    group: 'domestic',
  },
  {
    id: 'white-oak',
    name: 'White Oak',
    color: '#C2B280',
    oiledColor: '#A89860',
    textureId: 'oak',
    foodSafe: true,
    janka: 1360,
    densityLbFt3: 47,
    group: 'domestic',
    notes: 'Closed pore — food-safe unlike red oak.',
  },
  {
    id: 'red-oak',
    name: 'Red Oak',
    color: '#C19A6B',
    oiledColor: '#A67C52',
    textureId: 'oak',
    foodSafe: false,
    janka: 1290,
    densityLbFt3: 47,
    openPore: true,
    group: 'domestic',
    notes: 'Open pore — not recommended for cutting boards.',
  },
  {
    id: 'hickory',
    name: 'Hickory',
    color: '#BAA084',
    oiledColor: '#9C8468',
    textureId: 'hickory',
    foodSafe: true,
    janka: 1820,
    densityLbFt3: 50,
    group: 'domestic',
    notes: 'Very hard and durable — excellent for cutting boards.',
  },
  {
    id: 'ash',
    name: 'Ash',
    color: '#D2C4A8',
    oiledColor: '#B8A88C',
    textureId: 'ash',
    foodSafe: false,
    janka: 1320,
    densityLbFt3: 42,
    openPore: true,
    group: 'domestic',
    notes: 'Open pore — caution for food contact.',
  },
  {
    id: 'beech',
    name: 'Beech',
    color: '#C4A882',
    oiledColor: '#B8956A',
    textureId: 'beech',
    foodSafe: true,
    janka: 1300,
    densityLbFt3: 45,
    group: 'domestic',
  },
  {
    id: 'birch',
    name: 'Birch',
    color: '#DCC9A3',
    oiledColor: '#C9B48A',
    textureId: 'birch',
    foodSafe: true,
    janka: 1260,
    densityLbFt3: 42,
    group: 'domestic',
  },

  // ─── EXOTIC ─────────────────────────────────────────────────
  {
    id: 'sapele',
    name: 'Sapele',
    color: '#8A4B38',
    oiledColor: '#6E3A2C',
    textureId: 'sapele',
    foodSafe: true,
    janka: 1410,
    densityLbFt3: 42,
    group: 'exotic',
    notes: 'Mahogany alternative — interlocked grain, stable.',
  },
  {
    id: 'mahogany',
    name: 'Mahogany',
    color: '#6D3728',
    oiledColor: '#4E281D',
    textureId: 'mahogany',
    foodSafe: true,
    janka: 800,
    densityLbFt3: 31,
    group: 'exotic',
    notes: 'Softer than most — better for serving boards than cutting.',
  },
  {
    id: 'padauk',
    name: 'Padauk',
    color: '#B33B24',
    oiledColor: '#8B2E1A',
    textureId: 'padauk',
    foodSafe: true,
    janka: 1725,
    densityLbFt3: 45,
    group: 'exotic',
    notes: 'Accent only — fades toward brown over time.',
  },
  {
    id: 'purpleheart',
    name: 'Purpleheart',
    color: '#6B3A6B',
    oiledColor: '#4A2A4A',
    textureId: 'purpleheart',
    foodSafe: true,
    janka: 1860,
    densityLbFt3: 56,
    group: 'exotic',
    notes: 'Very hard — Janka mismatch with soft woods.',
  },
  {
    id: 'yellowheart',
    name: 'Yellowheart',
    color: '#F5C71A',
    oiledColor: '#D4A912',
    textureId: 'yellowheart',
    foodSafe: true,
    janka: 1790,
    densityLbFt3: 54,
    group: 'exotic',
    notes: 'Bright yellow accent — darkens slightly over time.',
  },
  {
    id: 'bloodwood',
    name: 'Bloodwood',
    color: '#6E1C1C',
    oiledColor: '#4A1414',
    textureId: 'bloodwood',
    foodSafe: true,
    janka: 2900,
    densityLbFt3: 62,
    group: 'exotic',
    notes: 'Extremely hard — use sparingly, Janka mismatch risk.',
  },
  {
    id: 'wenge',
    name: 'Wenge',
    color: '#362823',
    oiledColor: '#241A18',
    textureId: 'wenge',
    foodSafe: true,
    janka: 1930,
    densityLbFt3: 55,
    group: 'exotic',
    notes: 'Very dark accent — splinters easily, seal end grain.',
  },
  {
    id: 'bubinga',
    name: 'Bubinga',
    color: '#8F4E45',
    oiledColor: '#6E3A35',
    textureId: 'bubinga',
    foodSafe: true,
    janka: 1980,
    densityLbFt3: 56,
    group: 'exotic',
  },
  {
    id: 'jatoba',
    name: 'Jatoba',
    color: '#8F3E30',
    oiledColor: '#6E2F24',
    textureId: 'jatoba',
    foodSafe: true,
    janka: 2350,
    densityLbFt3: 57,
    group: 'exotic',
    notes: 'Brazilian cherry — very hard, darkens significantly.',
  },
  {
    id: 'teak',
    name: 'Teak',
    color: '#B8860B',
    oiledColor: '#8B6914',
    textureId: 'teak',
    foodSafe: true,
    janka: 1070,
    densityLbFt3: 41,
    oily: true,
    group: 'exotic',
    notes: 'Oily — wipe with solvent before glue.',
  },

  // ─── ACCENT ─────────────────────────────────────────────────
  {
    id: 'holly',
    name: 'Holly',
    color: '#FDFDF8',
    oiledColor: '#F0EDE5',
    textureId: 'holly',
    foodSafe: true,
    janka: 1020,
    densityLbFt3: 40,
    group: 'accent',
    notes: 'Whitest wood available — use for bright accents.',
  },
  {
    id: 'ebony',
    name: 'Ebony',
    color: '#1A1A1A',
    oiledColor: '#0D0D0D',
    textureId: 'ebony',
    foodSafe: true,
    janka: 3080,
    densityLbFt3: 68,
    group: 'accent',
    notes: 'Extremely hard and dense — accent only, very expensive.',
  },
];

export function getWood(id: string): Wood | undefined {
  return WOODS.find((w) => w.id === id);
}

export function getWoodOrThrow(id: string): Wood {
  const w = getWood(id);
  if (!w) throw new Error(`Unknown wood: ${id}`);
  return w;
}
